services:
  jupyter:
    image: "{{ cookiecutter.project_name }}:{{ cookiecutter.version }}"
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    env_file:
      - .env
